# .github/workflows/deploy_lambda.yml
name: Deploy Lambda Code

on:
  workflow_dispatch:

jobs:
  deploy_lambda:
    runs-on: [self-hosted, Linux, X64, aws, ipchecker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Package Lambda with dependencies
        run: |
          cd lambda
          mkdir -p package
          pip install requests -t package
          cp handler.py package/
          cd package
          zip -r9 ../../infra/lambda.zip .


      - name: Upload Lambda zip to S3
        run: aws s3 cp infra/lambda.zip s3://dlyogipchecker-bucket/lambda.zip

      - name: Create Lambda function (if not exists)
        run: |
          if aws lambda get-function --function-name dlyogipchecker >/dev/null 2>&1; then
            echo "☑️ Lambda function already exists."
          else
            ROLE_ARN=$(aws iam get-role --role-name dlyogipchecker-lambda-role --query 'Role.Arn' --output text)
            aws lambda create-function \
              --function-name dlyogipchecker \
              --runtime python3.11 \
              --handler handler.lambda_handler \
              --code S3Bucket=dlyogipchecker-bucket,S3Key=lambda.zip \
              --role "$ROLE_ARN" \
              --region us-west-2
          fi

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name dlyogipchecker \
            --s3-bucket dlyogipchecker-bucket \
            --s3-key lambda.zip \
            --region us-west-2
      
      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name dlyogipchecker \
            --environment "Variables={
              API_SECRET_KEY='${{ secrets.API_SECRET_KEY }}',
              SMTP_HOST='${{ secrets.SMTP_HOST }}',
              SMTP_PORT='${{ secrets.SMTP_PORT }}',
              SMTP_USER='${{ secrets.SMTP_USER }}',
              SMTP_PASSWORD='${{ secrets.SMTP_PASSWORD }}',
              PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }},
              TO_EMAIL='${{ secrets.TO_EMAIL }}
            }"
      
      - name: Increase Lambda timeout & memory
        run: |
          aws lambda update-function-configuration \
            --function-name dlyogipchecker \
            --timeout 30 \
            --memory-size 256 \
            --region us-west-2


