name: Deploy Lambda Code

on:
  workflow_dispatch:

jobs:
  deploy_lambda:
    runs-on: [self-hosted, Linux, X64, aws, ipchecker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Zip Lambda function
        run: |
          cd lambda
          zip ../infra/lambda.zip handler.py

      - name: Upload Lambda zip to S3
        run: aws s3 cp infra/lambda.zip s3://dlyogipchecker-bucket/lambda.zip

      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name dlyogipchecker \
            --s3-bucket dlyogipchecker-bucket \
            --s3-key lambda.zip \
            --region us-west-2
